export const items=[
    {
        id:1,
        nome:"item1",
        preco:10,
        img:"images/toa/picture-icon.png",
        quantidade:67,
        noCarrinho:0
    },
    {
        id:2,
        nome:"item2",
        preco:20,
        img:"images/toa/picture-icon.png",
        quantidade:34,
        noCarrinho:0
    },
    {
        id:3,
        nome:"item3",
        preco:13,
        img:"images/toa/picture-icon.png",
        quantidade:46,
        noCarrinho:0
    },
    {
        id:4,
        nome:"item4",
        preco:15,
        img:"images/toa/picture-icon.png",
        quantidade:88,
        noCarrinho:0
    },
    {
        id:5,
        nome:"item5",
        preco:7.5,
        img:"images/toa/picture-icon.png",
        quantidade:12,
        noCarrinho:0
    },
];